name: Continuous Integration

# defining when this file runs
on:
  push:
    branches: [ main ]

# defining job(or set of jobs)
jobs:
  run_tests:
    # define instance that I want to run this test on
    runs-on: ubuntu-latest

    # define overall strategy that this is going to run with
    strategy:
      # if any of set of test fail, then exit double thing -- avoid this and get matrix option
      fail-fast: false
      # github allows defining matrices
      matrix:
        python-version: [3.10]


    steps:
      # checkout the codebase
      # leverage github's built-in checkout action: chain other actions together to form overall setup
      - uses: actions/checkout@v2

      # install python
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install python dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run actual unit tests
      - name: Test with unittest
        run: |
          python -m unittest tests.test_root

